# Generated by Django 2.2.6 on 2019-11-02 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rescuemap', '0003_victim_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='situation',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='total_adults',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='total_children',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='total_elderly',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='info',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
