# Generated by Django 2.2.6 on 2019-11-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescuemap', '0004_auto_20191103_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='inside_dz',
            field=models.BooleanField(null=True),
        ),
    ]
