# Generated by Django 2.2.6 on 2019-11-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescuemap', '0009_auto_20191106_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='roof',
            field=models.CharField(default=False, max_length=10, null=True),
        ),
    ]
