# Generated by Django 2.2.6 on 2019-11-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescuemap', '0010_auto_20191106_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='name_2',
            field=models.CharField(default='', max_length=255),
        ),
    ]
