# Generated by Django 2.2.6 on 2019-11-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescuemap', '0011_victim_name_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='address',
            field=models.TextField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='info',
            field=models.TextField(default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='inside_dz',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='name_2',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='number_2',
            field=models.IntegerField(default='', null=True),
        ),
    ]
