# Generated by Django 2.2.13 on 2020-08-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescuemap', '0012_auto_20191106_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescueteam',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
