# Generated by Django 2.2.6 on 2019-10-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescuemap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='victim',
            name='info',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='victim',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='victim',
            name='roof',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
