# Generated by Django 2.2.6 on 2019-11-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescuemap', '0006_rescueteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescueteam',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rescueteam',
            name='profession',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='rescueteam',
            name='phone',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
